/**
 * Writes docs/contrast-audit.md from the measured audit in
 * src/audit/contrast-audit.ts, so the table is reviewable without running the
 * app and can never disagree with the tokens.
 *
 *   node scripts/audit-contrast.ts
 */

import { mkdirSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

import {
  auditSections,
  auditTotals,
  buildAudit,
  checkSpecAssertions,
  requirementLabel,
  type AuditRow,
} from '../src/audit/contrast-audit.ts'
import { planeLabels } from '../src/tokens/semantic.ts'

const projectRoot = join(dirname(fileURLToPath(import.meta.url)), '..')
const outputFile = join(projectRoot, 'docs', 'contrast-audit.md')

function ratio(row: AuditRow): string {
  return `${row.ratio.toFixed(2)}:1`
}

function verdictLabel(row: AuditRow): string {
  switch (row.verdict) {
    case 'pass':
      return 'Pass'
    case 'fail':
      return 'Fail'
    case 'documented':
      return 'Intentional, mitigated'
    case 'not applicable':
      return 'Not applicable'
  }
}

function backgroundCell(row: AuditRow): string {
  const over = row.backdrop === undefined ? '' : ` over \`${row.backdrop}\``
  return `\`${row.backgroundPrimitive}\` ${row.backgroundValue}${over}`
}

function sectionTable(rows: AuditRow[]): string {
  const header = [
    '| Plane | Foreground | Resolves to | Background | Resolves to | Ratio | Requirement | Result |',
    '|---|---|---|---|---|---|---|---|',
  ]
  const body = rows.map((row) =>
    [
      '',
      row.plane === 'tenant' ? 'Tenant' : 'Control',
      `\`${row.foreground}\``,
      `\`${row.foregroundPrimitive}\` ${row.foregroundValue}`,
      `\`${row.background}\``,
      backgroundCell(row),
      ratio(row),
      requirementLabel[row.requirement],
      verdictLabel(row),
      '',
    ].join(' | ').trim(),
  )
  return [...header, ...body].join('\n')
}

function notes(rows: AuditRow[]): string[] {
  return rows
    .filter((row) => row.verdict !== 'pass' && row.verdict !== 'not applicable')
    .map((row) => {
      const plane = row.plane === 'tenant' ? 'tenant' : 'control'
      const reason = row.mitigation ?? `${row.usage}; below the ${row.minimum?.toFixed(1)}:1 requirement`
      return `- \`${row.foreground}\` on \`${row.background}\`, ${plane} plane — ${reason}.`
    })
}

function main(): void {
  const rows = buildAudit()
  const totals = auditTotals(rows)
  const assertions = checkSpecAssertions()
  const disagreements = assertions.filter((entry) => !entry.agrees)

  const lines: string[] = [
    '# Contrast audit',
    '',
    'Generated by `npm run audit:contrast` from `src/audit/contrast-audit.ts`. Do not edit by hand.',
    '',
    'Every ratio is measured from the real token values with the WCAG 2.1 relative-luminance',
    'formula. Translucent values are flattened onto the surface they are painted over before',
    'measurement. Requirements are 4.5:1 for body text, 3:1 for large text, marks and the',
    'boundaries of interactive controls.',
    '',
    '## Result',
    '',
    `- Pairs measured: ${totals.measured}`,
    `- Pass: ${totals.pass}`,
    `- Fail: ${totals.fail}`,
    `- Intentional and mitigated: ${totals.documented}`,
    `- Not applicable (decorative): ${totals.notApplicable}`,
    '',
  ]

  for (const section of auditSections) {
    const sectionRows = rows.filter((row) => row.section === section.title)
    lines.push(`## ${section.title}`, '', section.description, '', sectionTable(sectionRows), '')
    const sectionNotes = notes(sectionRows)
    if (sectionNotes.length > 0) lines.push(...sectionNotes, '')
  }

  lines.push(
    '## Spec assertions',
    '',
    'The ratios asserted in admin-web-design.md section 5 ("Contrast rules"), re-measured with',
    'the same code.',
    '',
    '| Foreground | Background | Spec says | Measured | Agrees | Claim |',
    '|---|---|---|---|---|---|',
    ...assertions.map((entry) =>
      `| \`${entry.foreground}\` ${entry.foregroundValue} | \`${entry.background}\` ${entry.backgroundValue} | ${entry.asserted.toFixed(2)}:1 | ${entry.measured.toFixed(2)}:1 | ${entry.agrees ? 'Yes' : 'No'} | ${entry.claim} |`,
    ),
    '',
  )

  if (disagreements.length > 0) {
    lines.push(
      '### Disagreements',
      '',
      ...disagreements.map(
        (entry) =>
          `- \`${entry.foreground}\` ${entry.foregroundValue} on \`${entry.background}\` ${entry.backgroundValue}: the spec says ${entry.asserted.toFixed(2)}:1, measured ${entry.measured.toFixed(2)}:1.`,
      ),
      '',
    )
  }

  lines.push(
    '## Planes',
    '',
    ...Object.entries(planeLabels).map(([plane, label]) => `- \`data-plane="${plane}"\` — ${label}`),
    '',
  )

  mkdirSync(dirname(outputFile), { recursive: true })
  writeFileSync(outputFile, lines.join('\n'), 'utf8')

  console.log(`wrote docs/contrast-audit.md`)
  console.log(
    `${totals.measured} pairs measured: ${totals.pass} pass, ${totals.fail} fail, ${totals.documented} intentional, ${totals.notApplicable} decorative`,
  )
  if (disagreements.length > 0) {
    console.log(`${disagreements.length} spec assertion(s) disagree with the measured value`)
  }
  if (totals.fail > 0) {
    for (const row of rows.filter((entry) => entry.verdict === 'fail')) {
      console.log(`fail: ${row.foreground} on ${row.background} (${row.plane}) ${ratio(row)}`)
    }
  }
}

main()
