/**
 * Generates the CSS token layers from src/tokens/*.ts.
 *
 *   node scripts/tokens.ts           writes src/styles/*.css
 *   node scripts/tokens.ts --check   fails if the written CSS is stale
 *
 * The TypeScript token modules are the single source of truth. The generated
 * CSS is committed so the app has no build-time codegen dependency, and
 * `--check` runs before every build so the two cannot drift.
 */

import { mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, join, relative } from 'node:path'
import { fileURLToPath } from 'node:url'

import { assertComponentTokensResolve, componentTokens, componentGroups } from '../src/tokens/components.ts'
import { primitiveGroups, primitiveRef, primitives, toCssVar } from '../src/tokens/primitives.ts'
import { scaleGroups, scaleTokens, typeSteps } from '../src/tokens/scales.ts'
import { effectTokens, semanticGroups, semanticTokens } from '../src/tokens/semantic.ts'

const projectRoot = join(dirname(fileURLToPath(import.meta.url)), '..')
const stylesDir = join(projectRoot, 'src', 'styles')

const BANNER = `/*
 * Generated by \`npm run tokens:build\` from src/tokens/*.ts.
 * Do not edit by hand: edit the TypeScript source and regenerate.
 */`

function comment(note: string | undefined): string {
  return note === undefined ? '' : ` /* ${note} */`
}

function declaration(cssVar: string, value: string, note?: string): string {
  return `  ${cssVar}: ${value};${comment(note)}`
}

function primitivesCss(): string {
  const blocks = primitiveGroups.map((group) => {
    const lines = group.primitives.map((entry) => declaration(entry.cssVar, entry.value, entry.note))
    return [`  /* ${group.title} */`, ...lines].join('\n')
  })
  return [
    BANNER,
    '',
    '/* The only file in the project that may carry a raw colour value. */',
    ':root {',
    blocks.join('\n\n'),
    '}',
    '',
  ].join('\n')
}

function semanticCss(): string {
  const tenantBlocks = semanticGroups.map((group) => {
    const lines = group.tokens.map((entry) =>
      declaration(entry.cssVar, primitiveRef(entry.tenant), entry.note),
    )
    return [`  /* ${group.title} */`, ...lines].join('\n')
  })

  const tenantEffects = effectTokens.map((entry) => declaration(entry.cssVar, entry.tenant, entry.note))

  const controlBlocks = semanticGroups
    .map((group) => {
      const lines = group.tokens
        .filter((entry) => entry.tenant !== entry.control)
        .map((entry) => declaration(entry.cssVar, primitiveRef(entry.control)))
      return lines.length === 0 ? '' : [`  /* ${group.title} */`, ...lines].join('\n')
    })
    .filter(Boolean)

  const controlEffects = effectTokens
    .filter((entry) => entry.tenant !== entry.control)
    .map((entry) => declaration(entry.cssVar, entry.control))

  return [
    BANNER,
    '',
    '/*',
    ' * Tenant plane (light) is the default and also answers to an explicit',
    ' * [data-plane="tenant"] container, so a plane can be nested inside its',
    ' * opposite. Control plane (dark) lists only the roles that change; the rest',
    ' * inherit. Every value is a var() reference into the primitive layer.',
    ' */',
    ':root,',
    "[data-plane='tenant'] {",
    tenantBlocks.join('\n\n'),
    '',
    '  /* Elevation */',
    tenantEffects.join('\n'),
    '}',
    '',
    "[data-plane='control'] {",
    controlBlocks.join('\n\n'),
    '',
    '  /* Elevation */',
    controlEffects.join('\n'),
    '}',
    '',
  ].join('\n')
}

function scalesCss(): string {
  const blocks = scaleGroups.map((group) => {
    const lines = group.tokens.map((entry) => declaration(entry.cssVar, entry.value, entry.note))
    return [`  /* ${group.title} */`, ...lines].join('\n')
  })

  const transforms = typeSteps
    .filter((step) => step.transform !== undefined)
    .map((step) => declaration(toCssVar(`${step.name}.transform`), step.transform ?? 'none'))

  return [
    BANNER,
    '',
    '/* Type, spacing, target, radius and motion. Plane-independent. */',
    ':root {',
    blocks.join('\n\n'),
    '',
    '  /* Type transforms */',
    transforms.join('\n'),
    '}',
    '',
  ].join('\n')
}

function componentsCss(): string {
  const blocks = componentGroups.map((group) => {
    const lines = group.tokens.map((entry) => declaration(entry.cssVar, entry.value, entry.note))
    return [`  /* ${group.title} */`, ...lines].join('\n')
  })
  return [
    BANNER,
    '',
    '/*',
    ' * Component handles for Phase 2. Each resolves to a semantic or scale token,',
    ' * so a component picks up plane theming without knowing a plane exists.',
    ' *',
    ' * These are redeclared on every [data-plane] container on purpose: a custom',
    ' * property resolves its var() references where it is declared, so declaring',
    ' * them only on :root would freeze them to the root plane.',
    ' */',
    ':root,',
    '[data-plane] {',
    blocks.join('\n\n'),
    '}',
    '',
  ].join('\n')
}

const outputs: Array<{ file: string; contents: string }> = [
  { file: join(stylesDir, 'primitives.css'), contents: primitivesCss() },
  { file: join(stylesDir, 'semantic.css'), contents: semanticCss() },
  { file: join(stylesDir, 'scales.css'), contents: scalesCss() },
  { file: join(stylesDir, 'components.css'), contents: componentsCss() },
]

function normalize(text: string): string {
  return text.replace(/\r\n/g, '\n')
}

/** Two layers must never claim the same custom property name. */
function assertUniqueCssVars(): void {
  const seen = new Map<string, string>()
  const layers: Array<[string, Array<{ name: string; cssVar: string }>]> = [
    ['primitive', primitives],
    ['semantic', semanticTokens],
    ['effect', effectTokens],
    ['scale', scaleTokens],
    ['component', componentTokens],
  ]
  for (const [layer, tokens] of layers) {
    for (const entry of tokens) {
      const previous = seen.get(entry.cssVar)
      if (previous !== undefined) {
        throw new Error(`${entry.cssVar} is claimed twice: ${previous} and ${layer} ${entry.name}`)
      }
      seen.set(entry.cssVar, `${layer} ${entry.name}`)
    }
  }
}

function main(): void {
  assertUniqueCssVars()
  assertComponentTokensResolve()
  const checkOnly = process.argv.includes('--check')
  mkdirSync(stylesDir, { recursive: true })

  const stale: string[] = []
  for (const output of outputs) {
    const label = relative(projectRoot, output.file).replace(/\\/g, '/')
    if (checkOnly) {
      let current = ''
      try {
        current = readFileSync(output.file, 'utf8')
      } catch {
        stale.push(`${label} is missing`)
        continue
      }
      if (normalize(current) !== normalize(output.contents)) stale.push(`${label} is out of date`)
    } else {
      writeFileSync(output.file, output.contents, 'utf8')
      console.log(`wrote ${label}`)
    }
  }

  if (checkOnly) {
    if (stale.length > 0) {
      console.error('Token CSS has drifted from src/tokens:')
      for (const item of stale) console.error(`  ${item}`)
      console.error('Run `npm run tokens:build` and commit the result.')
      process.exit(1)
    }
    console.log('Token CSS matches src/tokens.')
  }
}

main()
